In [10]:
import pandas as pd

df = pd.read_csv('cleaned.csv')

df.head()

,Upvotes,Date,Title,Body Text,Link
0,10,1449121338,Breaking Through the Safeties,Finally heard back from all of my safeties! O...,https://www.reddit.com/r/collegeresults/commen...
1,9,1449874637,Virginia Tech ED Deferred :(,Demographics: In-state Asian male\n\nIntended ...,https://www.reddit.com/r/collegeresults/commen...
2,6,1449888267,Accepted To Middlebury ED,Middlebury ED (only application)\n\nno financi...,https://www.reddit.com/r/collegeresults/commen...
3,6,1449900824,Accepted to Vanderbilt School of Engineering ED,Schools: Vanderbilt University (Accepted ED)\n...,https://www.reddit.com/r/collegeresults/commen...
4,7,1449936672,Accepted into Duke Pratt ED,I was just accepted this past Thursday to my f...,https://www.reddit.com/r/collegeresults/commen...

In [11]:
df2 = df
df2.drop(['Upvotes', 'Date', 'Title', 'Link'], axis=1, inplace=True)
df2.head()

                                           Body Text
0  Finally heard back from all of my safeties!  O...
1  Demographics: In-state Asian male\n\nIntended ...
2  Middlebury ED (only application)\n\nno financi...
3  Schools: Vanderbilt University (Accepted ED)\n...
4  I was just accepted this past Thursday to my f...